swagger: '2.0'
info:
  version: 1.1.0
  title: Swagger Petstore
  contact: {}
  description: pet test API
host: petstore.swagger.io
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pets:
    get:
      description: List all pets
      summary: listPets
      tags:
        - pets
      operationId: listPets
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: limit
          in: query
          required: false
          type: integer
          format: int32
          description: How many items to return at one time (max 100)
      responses:
        '200':
          description: An paged array of pets
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
          headers:
            x-next:
              description: A link to the next page of responses
              type: string
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
          headers: {}
    post:
      description: Create a pet
      summary: createPets
      tags:
        - pets
      operationId: createPets
      deprecated: false
      produces:
        - application/json
      parameters: []
      responses:
        '201':
          description: Null response
          headers: {}
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
          headers: {}
  '/pets/{petId}':
    get:
      description: Info for a specific pet
      summary: showPetById
      tags:
        - pets
      operationId: showPetById
      deprecated: false
      produces:
        - application/json
      parameters:
        - name: petId
          in: path
          required: true
          type: string
          description: The id of the pet to retrieve
      responses:
        '200':
          description: Expected response to a valid request
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
          headers: {}
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
          headers: {}
definitions:
  Pet:
    title: Pet
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
    required:
      - id
      - name
  Error:
    title: Error
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
    required:
      - code
      - message
tags:
  - name: pets
    description: ''
